#!/bin/bash

# Define the target branch to compare with
target_branch="main"  # Replace with your desired branch name

# Function to get a list of changed files
get_changed_files() {
  git diff --name-only "$target_branch"
}

# Check if the target branch has been merged
if git branch --list --remote "origin/$target_branch" | grep "$target_branch" &> /dev/null; then
  echo "The $target_branch branch has been merged. Proceeding with Terraform apply..."

  # Run Terraform apply here
  terraform apply -auto-approve

  # Get a list of changed files
  changed_files=$(get_changed_files)

  # Count and print the number of changed files
  file_count=$(echo "$changed_files" | wc -l)
  echo "Number of changed files: $file_count"

  # Print the list of changed files
  echo "List of changed files:"
  echo "$changed_files"
else
  echo "The $target_branch branch has not been merged. Terraform apply is not required."
fi
